fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

bile_mo:
    resource: "@BileMoBundle/Controller/"
    type:     annotation
    prefix:   /
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
