auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /
    
client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

bile_mo:
    resource: "@BileMoBundle/Controller/"
    type:     annotation
    prefix:   /
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
