security:
    encoders:
        ClientBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user_provider:
            id: application_server.security.user_provider

    firewalls:
        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false
        api_doc:
            pattern: ^/api/doc
            security: false
        secured_area:
            pattern:    ^/
            fos_oauth:  true
            stateless:  true
        

    access_control:
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }