security:
    encoders:
        ClientBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: ClientBundle:User }

    firewalls:
        api:
            pattern: ^/
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'jwt_token_authenticator'
        main:
            pattern: ^/login
            anonymous: true
            form_login:
                # The route name that the login form submits to
                check_path: security_login_check
                login_path: security_login_form
            logout:
                # The route name the user can go to in order to logout
                path: security_logout
        api_doc:
            pattern: ^/api/doc
            security: false
            
    access_control:
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        