<?php

namespace BileMoBundle\Repository;

/**
 *FeatureCategoryRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}

