<?php

namespace BileMoBundle\Repository;

/**
 * PhoneBrandRepository
 *FunctionalityRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
